main: me.iatog.crossbow.plugin.LegacyCrossbowPlugin
name: LegacyCrossbow
version: ${project.version}
description: Crossbow created for legacy servers

commands:
  legacycrossbow:
    description: main command for LegacyCrossbow plugin